# -----
# These are configurable settings for Artemis.
# This settings file is read by `settings.py`.
# -----
# Which subreddit's wiki to get configuration information from.
wiki: translatorBOT
# Number of seconds Artemis waits in between isochronisms.
wait: 30
# Number of isochronisms to cycle before updating post frequency.
post_frequency_cycles: 50
# Number of chunks to split flair enforced subreddits into in order to
# retrieve their submissions.
num_chunks: 8
# We don't want to log common connection errors.
conn_errors:
    - 500 HTTP
    - 502 HTTP
    - 503 HTTP
    - 504 HTTP
    - RequestException
# The day of the month for monthly statistics functions to run.
# And the day of the month for monthly traffic functions to run.
day_action: 1
day_traffic: 4
# The hour daily statistics functions will run at in 24-hour time,
# (midnight UTC in this case).
action_time: 0
# The offset in hours for the userflair routine to run.
userflair_time_offset: 20
# The amount of hours to allow for the statistics routine to run.
action_window: 11
# Boolean governing whether or not the statistics routine writes locally
# (for testing purposes) or to subreddit wiki pages.
stats_local: False
# Subscriber estimator sample size, how many past days to calculate
# the future growth of a subreddit's subscribers.
subscriber_sample_size: 14
# How many days in the future do we want to stop estimating a subreddit
# subscriber milestone?
subscriber_milestone_upper: 730
# The subscriber milestone will be formatted as "days" if it is fewer
# than this amount. Otherwise, it'll be formatted as "months."
subscriber_milestone_format_days: 120
# The number of chunks to break subscriber searches into in order to
# expedite the process.
pushshift_subscriber_chunks: 7
# Pushshift started tracking subscriber data on this day:
pushshift_subscriber_start: "2018-03-15"
# The number of posts to check for historical top posts data with
# Pushshift.
pushshift_top_check_num: 750
# The number of Pushshift entries to display in statistics pages.
num_display: 5
# The number of past individual days to display subscriber data.
num_display_subscriber_days: 180
# Minimum and maximum ages (in secs) for Artemis to act on posts.
# The first variable is often used as a baseline for other times.
min_monitor_sec: 300
max_monitor_sec: 86400
# A subreddit has to have at least this many subscribers for statistics,
# and a minimum default amount for userflair statistics.
min_s_stats: 25
min_s_userflair: 50000
# The number of data entries to store, and how many posts to pull.
entries_to_keep: 12000
# Dividers for how many entries to keep of other databases.
# Derived from `entries_to_keep` above.
lines_to_keep_divider: 2
updated_to_keep_divider: 5
operations_to_keep_multiplier: 5
# Number of posts to get when pulling submissions.
max_get_posts: 800
min_get_posts: 175
# Number of old posts as a limit with pulling posts for recording at
# the end of a day.
old_post_limit: 10
# Historical day limit, the max number of past days we want to get
# historical data for.
hist_days_limit: 120
# Moderator invite limits to space out multiple invites at a time.
mod_invite_reg: 3
mod_invite_stats: 1
# Message and string limits for advanced mode settings. The first is for
# any custom message, the second is for the bot name and sign-off.
advanced_limit_msg: 500
advanced_limit_name: 20
# Minimum fuzz ratio for a message to be flaired.
min_fuzz_ratio: 90
# The time of the hour the monitor will check the widgets and log.
monitor_time_check: 15
# This is the number of minutes for minimum age of last log entry for
# the monitor routine.
monitor_time_interval: 60
# These are widget IDs on r/AssistantBOT for the various routines to
# check and update.
widget_operational_status: widget_142uuvol5mzqi
widget_statistics_update: widget_13xm3fwr0w9mu
widget_statistics_actions: widget_14159zz24snay
widget_statistics_public_table: widget_13xztx496z34h
# These are major subscriber milestones that a subreddit reaches.
milestones:
    - 10
    - 20
    - 25
    - 50
    - 100
    - 250
    - 500
    - 750
    - 1000
    - 2000
    - 2500
    - 3000
    - 4000
    - 5000
    - 6000
    - 7000
    - 7500
    - 8000
    - 9000
    - 10000
    - 15000
    - 20000
    - 25000
    - 30000
    - 40000
    - 50000
    - 60000
    - 70000
    - 75000
    - 80000
    - 90000
    - 100000
    - 150000
    - 200000
    - 250000
    - 300000
    - 400000
    - 500000
    - 600000
    - 700000
    - 750000
    - 800000
    - 900000
    - 1000000
    - 1250000
    - 1500000
    - 1750000
    - 2000000
    - 2500000
    - 3000000
    - 4000000
    - 5000000
    - 6000000
    - 7000000
    - 7500000
    - 8000000
    - 9000000
    - 10000000
    - 15000000
    - 20000000
    - 25000000
    - 30000000
# A list of saved post attributes, in addition to author and
# subreddit. These are additional ones for Artemis Stream.
stream_attributes:
    - author_flair_text
    - domain
    - id
    - is_self
    - is_video
    - link_flair_css_class
    - link_flair_template_id
    - link_flair_text
    - over_18
    - spoiler
    - subreddit_subscribers
    - title
# Attributes we want to include on the stats page.
stream_include_attributes:
    - is_self
    - over_18
    - spoiler
# The amount to pull for each chunk in Stream.
stream_pull_amount: 200
# The number of days' worth of posts to keep in the Stream database.
stream_days_kept: 60
# The number of days' worth of posts that the writer routine checks.
stream_post_writer_days: 1
